from(bucket: "telegraf")
  |> range(start: -5m)
  |> filter(fn: (r) => r["_measurement"] == "AdminLog")
  |> filter(fn: (r) => r["host"] == "cibccaprodwls1.na1.prod.azure")
  |> filter(fn: (r) => r["level"] == "ERROR")
  |> filter(fn: (r) => r["server"] == "cibccaprodwls1")
  |> filter(fn: (r) => r["source"] == "com.fnis.wms.core.intact.IntactPollerEJBBean")
  |> filter(fn: (r) => r["_field"] == "notice")
  |> count()
