from(bucket: "telegraf")
  |> range(start: -5m)
  |> filter(fn: (r) => r["_field"] == "StuckThreadCount")
  |> filter(fn: (r) => r["_measurement"] == "weblogic.ThreadPoolRuntime")
  |> group(columns: ["_field", "host", "_measurement"])
  |> max()
