from(bucket: "telegraf") 
  |> range (start: -10m) 
  |> filter (fn: (r) => r["_measurement"] == "cpu") 
  |> filter (fn: (r) =>  r["_field"] == "usage_idle")
  |> filter (fn: (r) => r["cpu"] == "cpu-total") 
  |> filter (fn: (r) => r["host"] != "cibccaproddb5.na1.prod.azure") 
  |> filter (fn: (r) => r["_value"] < 5 ) 
  |> count()
